src/Acme/PermissionBundle/Form/TTHCType.php
<?php
namespace Acme\PermissionBundle\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class TTHCType extends AbstractType{
    public function buildForm(FormBuilderInterface $builder, array $options){        
        $builder->add('nametthc','text',array(
            'label'=>'Tên TTHC'
        ))    
        ->add('idlinhvuc','entity',array(
            'class'=>'AcmePermissionBundle:Linhvuc',
            'property'=>'namedv',
            'label'=>'Lĩnh vực',
            'multiple'=>FALSE,
            'attr' => array('class'=>'styled'),
            'expanded'=>FALSE
        ))
        ->add('iddonvithuly','entity',array(
            'class'=>'AcmePermissionBundle:Donvithuly',
            'property'=>'namedonvithuly',
            'label'=>'Tên Đơn Vị Thụ Lý',
            'multiple'=>FALSE,
            'attr' => array('class'=>'styled'),
            'expanded'=>FALSE
        ))     
            ;
    }
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
        'data_class' => 'Acme\PermissionBundle\Entity\Tthc'
        ));
    }
    public function getName()
    {
        return 'tthc';
    }    
}

src/Acme/PermissionBundle/Controller/DefaultController.php
<?php

namespace Acme\PermissionBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
//    public function menuCreateAction()
//    {
//        $usr = $this->get('security.context')->getToken()->getUser();
//        $em = $this->getDoctrine()->getManager();
//        $functions = array();
//        foreach ($usr->getRole() as $role){
//            $temp = $em->createQuery('SELECT f from AcmePermissionBundle:Functions f '
//                    . 'JOIN f.groupfunction g '
//                    . 'JOIN g.role r '
//                    . 'WHERE r.id = :id')->setParameter('id',$role->getId())->getResult();
//            $functions = array_merge($temp,$functions);
//        }
//        return $this->render('AcmePermissionBundle:Default:menu.html.twig',array('functions' => $functions));
//    }
    
    
     public function groupFuncViewAction()
    {
        $usr = $this->get('security.context')->getToken()->getUser();
        $em = $this->getDoctrine()->getManager();
         $gfunc = array();
        foreach ($usr->getRole() as $role){
            $temp = $em->createQuery('SELECT g from AcmePermissionBundle:Groupfunction g '
                    . 'JOIN g.role r '
                    . 'WHERE r.id = :id')->setParameter('id',$role->getId())->getResult();
            $gfunc = array_merge($temp,$gfunc);
        }
        
        return $this->render('AcmePermissionBundle:Default:groupFuncView.html.twig',array('gfunc' => $gfunc));
    }
    
    public function indexAction(){
        return $this->render('AcmePermissionBundle:Admin:baseAdmin.html.twig');
    }
}

src/Acme/PermissionBundle/Resources/views/Default/groupFuncView.html.twig
{% for g in gfunc%}
    <li>
       <a class="expand">{{g.name}}<span></span></a>
            <ul>
                {% for f in g.functions %}
                <li>
                   <a href="{{path(f.path)}}" class="expand"><span>{{f.name}}</span></a>
                </li>
                {% endfor%}
            </ul>
    </li>    
{% endfor%}

src/Acme/PermissionBundle/Resources/views/Default/index.html.twig
Hello {{ name }}!

src/Acme/PermissionBundle/Resources/views/Default/menu.html.twig
{#{% for function in functions%}
    {% for g in function.groupfunction %}
            <li>
                   <a href="{{path(function.path)}}" class="expand"><span>{{function.name}}</span></a>
            </li>
    {% endfor%}
{% endfor%}#}